n = 2000;
sd = n/2;
A = spdiags([10*diag(eye(n)) -1*diag(eye(n))],[0 sd],n,n);
A(2:n,1)=1;%All rows 1st column
A(1,2:n)=1;%Allcolumns 1st row
A(n,1:n-1)=1;%All columns last row
A(1:n-1,n)=1;%All rows last column
Af = full(A);
b = ones(n,1);
b(2:2:n)=-1;
t1 = tic;
[Ls,Us]=lu(A);
ys = Ls\b;
xsolsp = Us\ys;
et1 = toc(t1);
t2=tic;
[L,U]=lu(Af);
y = L\b;
xsolfl = U\y;
et2 = toc(t2);
